### ISSUE TITLE
Missing little-endian conversion?

### ISSUE THREAD

**Issue by raybellis** [dagargo/emu3fs#1]
https://github.com/dagargo/emu3fs/blob/04adb9a0796c616455c8e1620703196de53746c2/super.c#L351

This happens to work on Intel machines which are little endian but looks like it would fail on a big-endian Linux machine (odd though that E-Mu chose a little endian format when the machines were mostly big endian).

**Comment by dagargo** [comment]
Hi @raybellis!

I totally forgot about this, sorry.

I have added a conversion for the parameter you mentioned. In fact, I replaced all the `cpu_to_le32` occurrences with `le32_to_cpu`, which is the right function to use.

As I do not have a non LE machine, I have added some tests to check if everything works as expected on other systems easily.

And thanks for your suggestion.

**Comment by raybellis** [comment]
No worries!   FWIW, your code has been very useful in helping me understand the format so that I could build the disc image browser at https://emu.tools/.    I didn't add E3 sample preview yet, but I'll get around to that at some point.

The E4 series uses a very similar FS structure, albeit with a more complicated directory structure to allow for the one level deep nesting.    Unlike the E3 / ESI series, though, the banks are themselves just plain E4B files that follow the IFF specification.

**Comment by dagargo** [comment]
Glad to hear this project is useful!
Good luck with yours!
